password: super_secure

server:
  applicationConnectors:
    - type: http
      port: 8080
    - type: https
      port: 8443
      keyStorePath: dropbookmarks.keystore
      keyStorePassword: super_secure
      validateCerts: false

database:
  driverClass: com.mysql.jdbc.Driver
  user: root
  url: jdbc:mysql://localhost:3306/DropBookmarks
